[package]
name = "toolkit"
version = "0.1.0"
edition = "2021"

[features]
wasm = ["dep:wasm-bindgen"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
nalgebra = "0.33.2"
wasm-bindgen = { version = "0.2.100", optional = true }
